openapi: 3.0.0
info:
  title: API Documentation
  version: 1.0.0
  description: This is the API documentation for the application.
servers:
  - url: http://localhost:5000
paths:
  /orders:
    post:
      summary: Create a new order
      tags:
        - Orders
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                customer_id:
                  type: integer
                product_id:
                  type: integer
                order_date:
                  type: string
                  format: date-time
                quantity:
                  type: integer
      responses:
        201:
          description: Order created successfully
  /orders/{order_id}:
    get:
      summary: Get an order by ID
      tags:
        - Orders
      parameters:
        - in: path
          name: order_id
          schema:
            type: integer
          required: true
      responses:
        200:
          description: Order retrieved successfully
    put:
      summary: Update an order by ID
      tags:
        - Orders
      parameters:
        - in: path
          name: order_id
          schema:
            type: integer
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                customer_id:
                  type: integer
                product_id:
                  type: integer
                order_date:
                  type: string
                  format: date-time
                quantity:
                  type: integer
      responses:
        200:
          description: Order updated successfully
    delete:
      summary: Delete an order by ID
      tags:
        - Orders
      parameters:
        - in: path
          name: order_id
          schema:
            type: integer
          required: true
      responses:
        204:
          description: Order deleted successfully
  /products:
    post:
      summary: Create a new product
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
                  format: float
      responses:
        201:
          description: Product created successfully
  /products/{product_id}:
    get:
      summary: Get a product by ID
      tags:
        - Products
      parameters:
        - in: path
          name: product_id
          schema:
            type: integer
          required: true
      responses:
        200:
          description: Product retrieved successfully
    put:
      summary: Update a product by ID
      tags:
        - Products
      parameters:
        - in: path
          name: product_id
          schema:
            type: integer
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
                  format: float
      responses:
        200:
          description: Product updated successfully
    delete:
      summary: Delete a product by ID
      tags:
        - Products
      parameters:
        - in: path
          name: product_id
          schema:
            type: integer
          required: true
      responses:
        204:
          description: Product deleted successfully
  /customer:
    post:
      summary: Create a new customer
      tags:
        - Customers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
      responses:
        201:
          description: Customer created successfully
  /customer/{customer_id}:
    get:
      summary: Get a customer by ID
      tags:
        - Customers
      parameters:
        - in: path
          name: customer_id
          schema:
            type: integer
          required: true
      responses:
        200:
          description: Customer retrieved successfully
    put:
      summary: Update a customer by ID
      tags:
        - Customers
      parameters:
        - in: path
          name: customer_id
          schema:
            type: integer
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
      responses:
        200:
          description: Customer updated successfully
    delete:
      summary: Delete a customer by ID
      tags:
        - Customers
      parameters:
        - in: path
          name: customer_id
          schema:
            type: integer
          required: true
      responses:
        204:
          description: Customer deleted successfully
  /customeraccount:
    post:
      summary: Create a new customer account
      tags:
        - Customer Accounts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                customer_id:
                  type: integer
                username:
                  type: string
                password_hash:
                  type: string
      responses:
        201:
          description: Customer account created successfully
  /customeraccount/{customeraccount_id}:
    get:
      summary: Get a customer account by ID
      tags:
        - Customer Accounts
      parameters:
        - in: path
          name: customeraccount_id
          schema:
            type: integer
          required: true
      responses:
        200:
          description: Customer account retrieved successfully
    put:
      summary: Update a customer account by ID
      tags:
        - Customer Accounts
      parameters:
        - in: path
          name: customeraccount_id
          schema:
            type: integer
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password_hash:
                  type: string
      responses:
        200:
          description: Customer account updated successfully
    delete:
      summary: Delete a customer account by ID
      tags:
        - Customer Accounts
      parameters:
        - in: path
          name: customeraccount_id
          schema:
            type: integer
          required: true
      responses:
        204:
          description: Customer account deleted successfully